<div class="container">
    <div class="jumbotron">
        <h1 class="display-3"><?php echo($this->title); ?></h1>
        <p class="lead"><?php echo($this->caption); ?></p>
        <p><?php echo(nl2br($this->description)); ?></p>
        <?php if(isset($this->debugData)): ?>
        <hr class="my-4">
        <p>
            <pre>
                <?php echo(htmlentities(print_r($this->debugData, true))); ?>
            </pre>
        </p>
        <?php endif; ?>
    </div>
</div>
